=== YasinRjs/MA1-Xml_DataAnalysis/Projet1.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:p1="http://www.xml.project1.ulb.ac.be"
        targetNamespace="http://www.xml.project1.ulb.ac.be"
        elementFormDefault="qualified">

  <element name= "bookshop">
    <complexType>
      <!-- No need MaxOccurs MinOccurs, both default 1 -->
      <element ref="p1:scientificProductsDepartement"/>
      <element ref="p1:leisureProductsDepartement"/>
    </complexType>
  </element>

  <element name="scientificProductsDepartement">
    <complexType>
      <element name="book" type="p1:scientificBook" minOccurs=0 maxOccurs="unbounded"/>
    </complexType>
  </element>

  <element name="leisureProductsDepartement">
    <complexType>
      <element name="book" type="p1:leisureBook" minOccurs=0 maxOccurs="unbounded"/>
    </complexType>
  </element>

  <!-- ======================= Start of books ======================= -->

  <complexType name="commonBookInformations">
    <sequence>
      <element name="title" type="string"/>
      <element name="publisher" type="string"/>
      <element name="yearOfPublication" type="positiveInteger"/>
    </sequence>
  </complexType>

  <complexType name="scientificBook">
    <complexContent>
      <extension base="p1:commonBookInformations">
        <sequence>
          <choice> <!-- à vérifier -->
            <element name="author" type="string" maxOccurs="unbounded"/>
            <element name="editor" type="string" maxOccurs="unbounded"/>
          </choice>
          <element name="abstract" type="string" minOccurs=0/>
          <element name="edition" type="string" minOccurs=0/>
          <element name="isbn" type="string" minOccurs=0/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="leisureBook">
    <complexContent>
      <extension base="p1:commonBookInformations">
        <sequence>
          <element name="author" type="string" maxOccurs="unbounded"/>
          <element name="edition" type="string" minOccurs=0/>
          <element name="pages" type="positiveInteger" minOccurs=0/>
          <attribute name="genre" type="possibleGenre" use="required"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>


  <!-- A check -->
  <simpleType name="possibleGenre">
    <restriction base="string">
      <enumeration value="thriller"/>
      <enumeration value="horror"/>
      <enumeration value="sci/fi"/>
      <enumeration value="romance"/>
      <enumeration value="literature"/>
    </restriction>
  </simpleType>

</schema>

=== YasinRjs/MA1-Xml_DataAnalysis/Test.xml
<?xml version="1.0" encoding="utf-8"?>

<bookshop xmlns="http://www.xml.project1.ulb.ac.be"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.xml.project1.ulb.ac.be
            Projet1.xsd">

  <scientificProductsDepartement>
    <book>
      <title> La Base </title>
      <publisher> Yasin </publisher>
      <yearOfPublication> 2020 </yearOfPublication>
      <author> Yasin </author>
      <author> Jacky </author>
      <edition> Fortnite </edition>
    </book>
    <book>
      <title> Pleasant Park </title>
      <publisher> Jacky </publisher>
      <yearOfPublication> 2022 </yearOfPublication>
      <editor> Yasin2 </editor>
      <editor> Jacky2 </editor>
      <edition> Fortnite </edition>
      <abstract> Draré on saute à pleasant park </abstract>
    </book>
  </scientificProductsDepartement>

  <leisureProductsDepartement>
    <book genre="thriller">
      <title> this is a leisurebook </title>
      <publisher> Yasin </publisher>
      <yearOfPublication> 2020 </yearOfPublication>
      <author> Qqun </author>
      <edition>ta mere</edition>
      <pages> 1235423 </pages>
    </book>
  </leisureProductsDepartement>
</bookshop>

=== YasinRjs/MA1-Xml_DataAnalysis/Project1/Test2.xml
<?xml version="1.0" encoding="utf-8"?>

<bookshop xmlns="http://www.xml.project1.ulb.ac.be"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.xml.project1.ulb.ac.be
            Projet1.xsd">

  <scientificProductsDepartement>
  </scientificProductsDepartement>

  <leisureProductsDepartement>
    <book genre="thriller">
      <title> this is a leisurebook </title>
      <publisher> Yasin </publisher>
      <yearOfPublication> 2020 </yearOfPublication>
      <author> Qqun </author>
      <edition>Gentil</edition>
      <pages> 1235423 </pages>
    </book>

    <book genre="horror">
      <title> XML is life </title>
      <publisher> ULB </publisher>
      <yearOfPublication> 2018 </yearOfPublication>
      <author> Stijn Vansummeren </author>
      <pages> 145 </pages>
    </book>

    <periodical>
      <title> Koh-Lanta </title>
      <price> 100 </price>
      <publisher> TF1 </publisher>
    </periodical>
  </leisureProductsDepartement>


</bookshop>
